### PR TITLE
Make generator preserve string break for properties

### PR DESCRIPTION
**Pull request by erem2k**
Addresses #4 
Extended `generate_string` method for generator and added couple of parameters for string gen test to cover new use case

### CODE REVIEW

**Comment by erem2k** [comment]
Not exactly sure if strings in arrays can be broken up in similar fashion, hence leaving old generator logic for them specifically

**Comment by overfl0** [comment]
Hey! I just wanted to acknowledge that I've seen your PR - I just can't devote time to take a look at it and test it right now, especially that I'm not that good in SQF & Co. so I'll probably have to ask someone else to take a look as well.

I'll try going back to this PR as soon as I can! :)

**Comment by erem2k** [comment]
Not a problem - thanks for letting me know!
For now it can be worked around by subclassing the generator and implementing/copying a fix there, so it's not a blocking bug

**Review by overfl0 — APPROVED** [review]
If I said that I'll review and merge this PR, then I'll do it! You don't need to remind me every half a year! ;)

**Pull request merged**
