### PR TITLE
add search function

### PR DESCRIPTION
**Pull request by Th3Dilli**
Added the ability to search the parsed config kinda like you would in arma sqf syntax.

added parsing of `delete classname;`
added parsing of `array[] += {1,2,3};`

also added test for the new things and since i added another file for the search function tests i changed the travis yaml too

Since i am using vscode autoformated the code with autopepe8, if you dont like it that way let me know.

### CODE REVIEW

**Comment by overfl0** [comment]
Hey, sorry for it taking so long but as I said elsewhere I didn't have that much time to do pretty much anything.

Two things: could you split the PR into at least two? At least the search separate to the rest? I'm asking because I don't know for sure if that functionality should be handled by this library and would have to think about this a bit more.

The other part, there is no problem getting that in.

The worst case scenario would be that I'd merge the rest and release a package on pypi and you'd just reuse your code from the PR and simply use armaclass as a pip dependency for your own lib.

The other thing is: are you using a code formatter or something like that? Because I see that you've broken a few lines in two, without any other changes to them. I'm using 120 chars wide lines (yeah, I know, _Black_ opted for 88) and would prefer to keep it that way. Some other style changes that I've seen that you've added are okay.

**Comment by Th3Dilli** [comment]
Hey, no worries

i removed the search feature and changed the formatting to comply with yours.
Something i stumbled up on was that you can specify a pyproject.toml to enforce such things like formatting styles but i havnt looked further into it so maybe you wanna consider that to make it more easy in the future ;)

**Comment by overfl0** [comment]
I've asked on Discord and people like Dedmen and Mikero seem to disagree on the correctness of the new test for `delete`, which may mean that the implementation can also be incorrect.

I'd suggest taking a look as the conversation here: https://discord.com/channels/105462288051380224/105464579600977920/826451790500986911

Regarding the code formatting, I double-checked pep8 and I was, in fact, doing it wrong 😳 , however I much prefer the style of:
```python
function(
    args, args2,
    args3, args4)
```
over
```python
function(args, args2,
         args3, args4)
```

But from what i can see, the strings in that file are all over the place anyway (with lengths of much over 120 chars) so I'll probably just reformat them later anyway, after merging your PR.

> Something i stumbled up on was that you can specify a pyproject.toml to enforce such things like formatting styles but i havnt looked further into it so maybe you wanna consider that to make it more easy in the future ;)

Yeah, this could be a good idea. Maybe adding pep8 or flake8 (no Black because... of reasons 🙄 ) would make sense. I've never done that because this was supposed to be a small project for something I needed, at the time, and it simply evolved into something that I thought would make sense to release.

**Comment by Th3Dilli** [comment]
Oh yeah i looked at the conversation. I think i mad a not optimal test it was not the intention to create a class and then delete it 
it should have been like so: 
```py
    def test_delete(self):
        expected = {'Foo': {}}
        result = parse(
            'class Foo {\r\ndelete Moo; };')
        self.assertEqual(result, expected)
```

so basically Foo is probably inheriting from something and that brings the Moo class/attribute and in this test i am deleting that Moo class/attribute so the Foo class is empty after that.

I ll change it to that if you can agree on that?

**Pull request merged**
